package net.it_tim.dude_of_ping3.database;

// Generated 30 трав 2011 16:21:40 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Hosts generated by hbm2java
 */
public class Hosts implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String ip;
	private String description;
	private Boolean tocheck;
	private Set<TemperatureHistory> temperatureHistories = new HashSet<TemperatureHistory>(
			0);
	private Set<PowerHistory> powerHistories = new HashSet<PowerHistory>(0);
	private Set<KnockHistory> knockHistories = new HashSet<KnockHistory>(0);
	private Set<DoorHistory> doorHistories = new HashSet<DoorHistory>(0);

	public Hosts() {
	}

	public Hosts(int id) {
		this.id = id;
	}

	public Hosts(int id, String ip, String description, Boolean tocheck,
			Set<TemperatureHistory> temperatureHistories,
			Set<PowerHistory> powerHistories, Set<KnockHistory> knockHistories,
			Set<DoorHistory> doorHistories) {
		this.id = id;
		this.ip = ip;
		this.description = description;
		this.tocheck = tocheck;
		this.temperatureHistories = temperatureHistories;
		this.powerHistories = powerHistories;
		this.knockHistories = knockHistories;
		this.doorHistories = doorHistories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getTocheck() {
		return this.tocheck;
	}

	public void setTocheck(Boolean tocheck) {
		this.tocheck = tocheck;
	}

	public Set<TemperatureHistory> getTemperatureHistories() {
		return this.temperatureHistories;
	}

	public void setTemperatureHistories(
			Set<TemperatureHistory> temperatureHistories) {
		this.temperatureHistories = temperatureHistories;
	}

	public Set<PowerHistory> getPowerHistories() {
		return this.powerHistories;
	}

	public void setPowerHistories(Set<PowerHistory> powerHistories) {
		this.powerHistories = powerHistories;
	}

	public Set<KnockHistory> getKnockHistories() {
		return this.knockHistories;
	}

	public void setKnockHistories(Set<KnockHistory> knockHistories) {
		this.knockHistories = knockHistories;
	}

	public Set<DoorHistory> getDoorHistories() {
		return this.doorHistories;
	}

	public void setDoorHistories(Set<DoorHistory> doorHistories) {
		this.doorHistories = doorHistories;
	}

}
