package net.it_tim.dude_of_ping3.database;

// Generated 30 трав 2011 16:21:40 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * TemperatureHistory generated by hbm2java
 */
public class TemperatureHistory implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Hosts hosts;
	private Float temperature;
	private Date time;

	public TemperatureHistory() {
	}

	public TemperatureHistory(int id) {
		this.id = id;
	}

	public TemperatureHistory(int id, Hosts hosts, Float temperature, Date time) {
		this.id = id;
		this.hosts = hosts;
		this.temperature = temperature;
		this.time = time;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Float getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Float temperature) {
		this.temperature = temperature;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
