package net.it_tim.dude_of_ping3.database;

// Generated 30 трав 2011 16:21:40 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String login;
	private String password;
	private String name;
	private String surname;
	private Boolean hasAdminPerm;
	private Boolean hasViewPerm;
	private Boolean hasOperatorPerm;
	private Set<UserActionHistory> userActionHistories = new HashSet<UserActionHistory>(
			0);

	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Users(int id, String login, String password, String name,
			String surname, Boolean hasAdminPerm, Boolean hasViewPerm,
			Boolean hasOperatorPerm, Set<UserActionHistory> userActionHistories) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.hasAdminPerm = hasAdminPerm;
		this.hasViewPerm = hasViewPerm;
		this.hasOperatorPerm = hasOperatorPerm;
		this.userActionHistories = userActionHistories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Boolean getHasAdminPerm() {
		return this.hasAdminPerm;
	}

	public void setHasAdminPerm(Boolean hasAdminPerm) {
		this.hasAdminPerm = hasAdminPerm;
	}

	public Boolean getHasViewPerm() {
		return this.hasViewPerm;
	}

	public void setHasViewPerm(Boolean hasViewPerm) {
		this.hasViewPerm = hasViewPerm;
	}

	public Boolean getHasOperatorPerm() {
		return this.hasOperatorPerm;
	}

	public void setHasOperatorPerm(Boolean hasOperatorPerm) {
		this.hasOperatorPerm = hasOperatorPerm;
	}

	public Set<UserActionHistory> getUserActionHistories() {
		return this.userActionHistories;
	}

	public void setUserActionHistories(
			Set<UserActionHistory> userActionHistories) {
		this.userActionHistories = userActionHistories;
	}

}
